version: 2

#
# Jobs
#

jobs:

  # This job builds the base project directory (e.g. ~/package.json)
  build:
    docker:
      - image: circleci/node:6@sha256:cd06069d65e1eed780cde63ef50daeb982d98fdd37ab584fd93b72c535416d3a
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  # This job runs the lint tool on the whole repository
  lint:
    docker:
      - image: circleci/node:6@sha256:cd06069d65e1eed780cde63ef50daeb982d98fdd37ab584fd93b72c535416d3a
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}              
      - run:
          name: Security check
          command: npm run security-check
      - run:
          name: Lint
          command: npm run lint          

  # runs the unit tests
  unit-test:
    docker:
      - image: circleci/node:6@sha256:cd06069d65e1eed780cde63ef50daeb982d98fdd37ab584fd93b72c535416d3a
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Unit tests
          command: |
            npm run test &&
            ./node_modules/.bin/nyc report --temp-directory=coverage --reporter=text-lcov | ./node_modules/.bin/coveralls

  release:
    docker:
      - image: circleci/node:8@sha256:adb767629c708c5b735f9d7688236f6c61ac701f59c1ce826591d616f3e3544a
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run semantic-release

#
# Workflows
#

workflows:
  version: 2

  build_test_release:
    jobs:
      - build
      - lint:     
          requires:
            - build
      - unit-test:
          requires:
            - build
      - release:
          requires:
            - lint
            - unit-test
          filters:
            branches:
              only: master
